#!/usr/bin/env ruby

$LOAD_PATH.unshift File.expand_path("../lib", __FILE__)
require "obs"

# From https://github.com/mvidner/code-explorer/blob/68bacb7be22e5a20795bec21d581e982d9f6a145/lib/code_explorer/dot.rb
# @param graph [Hash{String => Array<String>}] vertex -> reachable vertices
# @param hrefs [Hash{String => String}]        vertex -> href
def dot_from_hash(graph, hrefs = {})
  dot = ""
  dot << "digraph g {\n"
  dot << "rankdir=LR;\n"
  graph.keys.sort.each do |vertex|
    href = hrefs[vertex]
    href = "href=\"#{href}\" " if href

    dot << "\"#{vertex}\"[#{href}];\n"
    destinations = graph[vertex].sort
    destinations.each do |d|
      dot << "\"#{vertex}\" -> \"#{d}\";\n"
    end
  end
  dot << "}\n"
  dot
end

project3 = OBS::Project3.new(ARGV[0], ARGV[1], ARGV[2])
deps = project3.dependson
puts dot_from_hash(deps)
